<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYVFZr1e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYVFZr1e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYVFZr1e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYVFZr1e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYVFZr1e\App_KernelDevDebugContainer([
    'container.build_hash' => 'YVFZr1e',
    'container.build_id' => 'e47420aa',
    'container.build_time' => 1684750370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYVFZr1e');
